import type { Metadata } from "next";
import "./globals.css";
import { Playfair_Display as PlayfairDisplay, Montserrat } from 'next/font/google'
import LenisWrapper from "./lib/LenisWrapper";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const sans = Montserrat({
  subsets: ['latin'],
  variable: '--font-sans',
  weight: ['200', '300', '400']
})
const serif = PlayfairDisplay({
  subsets: ['latin'],
  variable: '--font-serif',
  weight: ['400', '500', '600']
})

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  return (
    <html lang="en" className={`${sans.variable} ${serif.variable}`}>
      <meta name="viewport" content="width=device-width, initial-scale=1.0" />

      <LenisWrapper >
        <body>
          {children}
        </body>
      </LenisWrapper>
    </html>
  )
}